### ISSUE TITLE
TypeError: concatenate() got an unexpected keyword argument 'ignore_time_axes'" under the Out of Sample Forecast section.

### ISSUE THREAD

**Issue by DatAnalyticsAi** [h3ik0th/ES_energy_Transformer#4]
Dear Sir/Madam
I am seeking your help to run the Jupyter Notebook of this project. I am getting an error, see page 41 of the attached output showing an error message "TypeError: concatenate() got an unexpected keyword argument 'ignore_time_axes'" under the Out of Sample Forecast section.
Your assistance is appreciated.
Thank you.
Gwin.
 
[Energy_TFT error.docx](https://github.com/h3ik0th/ES_energy_Transformer/files/10088363/Energy_TFT.error.docx)

**Comment by h3ik0th** [comment]
It seems the Darts developers have changed the parameter name within the past few months from axes to axis, probably because the plural was a typo. https://unit8co.github.io/darts/generated_api/darts.timeseries.html?highlight=concatenate#darts.timeseries.TimeSeries.concatenate
Try "ignore_time_axis", according to their current API reference for concatenate.
